Traceback (most recent call last):
  File "cartpole.py", line 58, in <module>
    qvals = m(torch.tensor(obs))
  File "C:\Users\dqvin\anaconda3\envs\pygame_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Programming\project\MsPacman\dqn.py", line 197, in forward
    return self.net(x)
  File "C:\Users\dqvin\anaconda3\envs\pygame_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\dqvin\anaconda3\envs\pygame_env\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Users\dqvin\anaconda3\envs\pygame_env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\dqvin\anaconda3\envs\pygame_env\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat2 in method wrapper_mm)